plugins {
    id 'java-platform'
    id 'datev.publish-conventions'
}

description = 'A Bill of Materials aligning the Java 17 DATEV Buchungsstapel and EXTF exporter modules.'

dependencies {
    constraints {
        api project(':datev-exporter-core')
        api project(':datev-exporter-plain')
        api project(':datev-exporter-advanced-univocity')
        api project(':datev-exporter-field-validator')
        api project(':datev-exporter-advanced')
    }
}
