plugins {
    id 'datev.java-conventions'
    id 'datev.publish-conventions'
}

description = 'A Univocity-backed Java library for writing fixed-schema DATEV Buchungsstapel CSV files.'
ext.datevModuleName = 'io.github.mrtyldr.datev.univocity'

dependencies {
    testImplementation testFixtures(project(':datev-exporter-core'))

    api project(':datev-exporter-core')

    api 'com.univocity:univocity-parsers:2.9.1'
}
