plugins {
    id 'datev.java-conventions'
    id 'datev.publish-conventions'
}

description = 'A Java library for creating validated DATEV Buchungsstapel v13 CSV files.'
ext.datevModuleName = 'io.github.mrtyldr.datev.advanced'

dependencies {
    testImplementation testFixtures(project(':datev-exporter-core'))

    api project(':datev-exporter-core')

    api 'com.univocity:univocity-parsers:2.9.1'

    testImplementation project(':datev-exporter-plain')
    testImplementation project(':datev-exporter-univocity')
    testImplementation project(':datev-exporter-field-validator')
}
