plugins {
    id 'datev.java-conventions'
    id 'datev.publish-conventions'
}

description = 'A Java 17 DATEV Buchungsstapel v13/v12 writer with built-in validation and optional custom downstream CSV headers.'
ext.datevModuleName = 'io.github.mrtyldr.datev.advanced'

dependencies {
    testImplementation testFixtures(project(':datev-exporter-core'))

    api project(':datev-exporter-core')


    testImplementation project(':datev-exporter-plain')
    testImplementation project(':datev-exporter-field-validator')
}
