plugins {
    id 'datev.java-conventions'
    id 'datev.publish-conventions'
}

description = 'A Java 17 writer for complete DATEV Buchungsstapel and EXTF v13/v12 files with retained and forward-only streaming APIs.'
ext.datevModuleName = 'io.github.mrtyldr.datev.plain'

dependencies {
    testImplementation testFixtures(project(':datev-exporter-core'))

    api project(':datev-exporter-core')
}
