plugins {
    id 'datev.java-conventions'
    id 'datev.publish-conventions'
}

description = 'Univocity interoperability for the advanced DATEV Buchungsstapel exporter.'
ext.datevModuleName = 'io.github.mrtyldr.datev.advanced.univocity'

dependencies {
    testImplementation testFixtures(project(':datev-exporter-core'))

    api project(':datev-exporter-advanced')

    api 'com.univocity:univocity-parsers:2.9.1'

    testImplementation project(':datev-exporter-plain')
    testImplementation project(':datev-exporter-field-validator')
}
