plugins {
    id 'datev.java-conventions'
    id 'datev.publish-conventions'
}

description = 'Univocity CsvWriter interoperability for DATEV Buchungsstapel v13/v12 heading-and-booking-row output and custom CSV schemas.'
ext.datevModuleName = 'io.github.mrtyldr.datev.advanced.univocity'

dependencies {
    testImplementation testFixtures(project(':datev-exporter-core'))

    api project(':datev-exporter-advanced')

    api 'com.univocity:univocity-parsers:2.9.1'

    testImplementation project(':datev-exporter-plain')
    testImplementation project(':datev-exporter-field-validator')
}
